# Funding links for robot-framework-optimizer-core
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - https://kobolcs.github.io/robot-optimizer-pro
