# tests/integration/test_cli_subprocess.py
"""Component / integration tests for the CLI via subprocess (Task 27).

These tests exercise the full command including entry-point resolution,
exit codes, and output format — not just the internal ``_run_analyze`` helper.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest


def _run(*args: str, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    """Run robot-optimizer as a module so it works without install."""
    cmd = [sys.executable, "-m", "robot_optimizer_core", *args]
    env = os.environ.copy()
    src_dir = Path(__file__).resolve().parents[2] / "src"
    existing_pythonpath = env.get("PYTHONPATH")
    env["PYTHONPATH"] = (
        str(src_dir)
        if not existing_pythonpath
        else f"{src_dir}{os.pathsep}{existing_pythonpath}"
    )
    # Force UTF-8 for stdin/stdout/stderr in the subprocess and decoding here.
    # Windows defaults to cp1252, which corrupts non-ASCII output (e.g. em-dashes
    # in CLI messages) and can raise UnicodeDecodeError when capturing output.
    env.setdefault("PYTHONIOENCODING", "utf-8")
    env.setdefault("PYTHONUTF8", "1")
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        cwd=cwd,
        env=env,
    )


# ---------------------------------------------------------------------------
# --version
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestVersionSubprocess:
    def test_version_exits_zero(self) -> None:
        result = _run("--version")
        assert result.returncode == 0
        assert "robot-optimizer" in result.stdout.lower() or result.returncode == 0


# ---------------------------------------------------------------------------
# analyze — exit codes
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestAnalyzeExitCodesSubprocess:
    def test_clean_file_exits_zero(self, tmp_path: Path) -> None:
        """A file with no findings should exit 0."""
        f = tmp_path / "clean.robot"
        f.write_bytes(b"*** Test Cases ***\nMy Test\n    Log    hello\n")
        result = _run("analyze", str(f))
        # Exit 0 or 1 (findings may be generated by default analyzers)
        assert result.returncode in (0, 1)

    def test_missing_path_exits_two(self, tmp_path: Path) -> None:
        """A nonexistent path must exit with code 2."""
        result = _run("analyze", str(tmp_path / "nosuchfile.robot"))
        assert result.returncode == 2

    def test_no_fail_exits_zero(self, tmp_path: Path) -> None:
        """--no-fail must produce exit 0 even when findings exist."""
        f = tmp_path / "t.robot"
        f.write_bytes(b"*** Test Cases ***\nMy Test\n    Sleep    10\n")
        result = _run("analyze", str(f), "--no-fail")
        assert result.returncode == 0


# ---------------------------------------------------------------------------
# analyze — output format
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestAnalyzeFormatSubprocess:
    def test_json_output_is_valid_json(self, tmp_path: Path) -> None:
        f = tmp_path / "t.robot"
        f.write_bytes(b"*** Test Cases ***\nMy Test\n    Sleep    10\n")
        result = _run("analyze", str(f), "--format", "json")
        parsed = json.loads(result.stdout)
        assert isinstance(parsed, list)

    def test_text_output_contains_finding_info(self, tmp_path: Path) -> None:
        f = tmp_path / "t.robot"
        f.write_bytes(b"*** Test Cases ***\nMy Test\n    Sleep    10\n")
        result = _run("analyze", str(f), "--format", "text")
        # Either findings or a clean message
        assert result.stdout


# ---------------------------------------------------------------------------
# analyze — --min-severity
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestMinSeveritySubprocess:
    def test_min_severity_error_filters_warnings(self, tmp_path: Path) -> None:
        """With --min-severity ERROR, WARNING findings must not appear."""
        f = tmp_path / "t.robot"
        f.write_bytes(b"*** Test Cases ***\nMy Test\n    Sleep    2\n")
        result = _run("analyze", str(f), "--format", "json", "--min-severity", "ERROR")
        findings = json.loads(result.stdout)
        severities = {finding["severity"] for finding in findings}
        assert "WARNING" not in severities
        assert "INFO" not in severities

    def test_invalid_min_severity_exits_two(self, tmp_path: Path) -> None:
        f = tmp_path / "t.robot"
        f.write_bytes(b"*** Test Cases ***\nMy Test\n    Log    hi\n")
        result = _run("analyze", str(f), "--min-severity", "CRITICAL")
        assert result.returncode == 2


# ---------------------------------------------------------------------------
# list-analyzers
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestListAnalyzersSubprocess:
    def test_list_analyzers_text_exits_zero(self) -> None:
        result = _run("list-analyzers")
        assert result.returncode == 0
        assert "dead_code" in result.stdout

    def test_list_analyzers_json_is_valid(self) -> None:
        result = _run("list-analyzers", "--format", "json")
        assert result.returncode == 0
        # Extract the JSON array from stdout (logs may precede it)
        parsed = json.loads(result.stdout)
        assert isinstance(parsed, list)
        names = [r["name"] for r in parsed]
        assert "dead_code" in names
        assert "sleep_detector" in names
        assert "naming_convention" in names

    def test_all_new_analyzers_listed(self) -> None:
        result = _run("list-analyzers", "--format", "json")
        parsed = json.loads(result.stdout)
        names = {r["name"] for r in parsed}
        expected = {
            "dead_code",
            "sleep_detector",
            "hardcoded_value",
            "naming_convention",
            "setup_teardown",
            "tag_consistency",
            "test_documentation",
        }
        assert expected.issubset(names)

    def test_list_analyzers_stdout_has_no_structured_logs(self) -> None:
        result = _run("list-analyzers")
        assert result.returncode == 0
        assert '{"timestamp":' not in result.stdout


@pytest.mark.integration
class TestHtmlFormatSubprocess:
    def test_html_output_contains_expected_sections(self) -> None:
        demo = Path(__file__).resolve().parents[2] / "examples" / "bad_robot_suite"
        result = _run("analyze", str(demo), "--format", "html", "--no-fail")
        assert result.returncode == 0
        assert "<html" in result.stdout.lower()
        assert "Robot Framework Suite Health Report" in result.stdout
        assert "Executive summary" in result.stdout
        assert "Recommended actions" in result.stdout
        assert "Appendix — Detailed Findings" in result.stdout

    def test_html_output_file_writes_without_dumping_html(self, tmp_path: Path) -> None:
        demo = Path(__file__).resolve().parents[2] / "examples" / "bad_robot_suite"
        out = tmp_path / "report.html"
        result = _run(
            "analyze",
            str(demo),
            "--format",
            "html",
            "--output-file",
            str(out),
            "--no-fail",
        )
        assert result.returncode == 0
        assert out.exists()
        assert "<html" in out.read_text(encoding="utf-8").lower()
        assert "Results written to" in result.stdout
        assert "Robot Framework Suite Health Report" not in result.stdout


# ---------------------------------------------------------------------------
# --baseline / --update-baseline
# ---------------------------------------------------------------------------

_SLEEP_ROBOT = """\
*** Settings ***
Library    BuiltIn

*** Test Cases ***
My Slow Test
    Sleep    2s
    Log    done
"""


@pytest.mark.integration
class TestBaselineSubprocess:
    def test_first_run_creates_baseline_file(self, tmp_path: Path) -> None:
        robot_file = tmp_path / "suite.robot"
        robot_file.write_text(_SLEEP_ROBOT, encoding="utf-8")
        baseline = tmp_path / "baseline.json"

        result = _run("analyze", str(robot_file), "--baseline", str(baseline), "--no-fail")

        assert result.returncode == 0
        assert baseline.exists()
        assert "baseline" in result.stderr.lower()

    def test_first_run_writes_findings_to_baseline(self, tmp_path: Path) -> None:
        robot_file = tmp_path / "suite.robot"
        robot_file.write_text(_SLEEP_ROBOT, encoding="utf-8")
        baseline = tmp_path / "baseline.json"

        _run("analyze", str(robot_file), "--baseline", str(baseline), "--no-fail")

        import json as _json
        data = _json.loads(baseline.read_text(encoding="utf-8"))
        assert isinstance(data, list)

    def test_second_run_suppresses_baseline_findings(self, tmp_path: Path) -> None:
        robot_file = tmp_path / "suite.robot"
        robot_file.write_text(_SLEEP_ROBOT, encoding="utf-8")
        baseline = tmp_path / "baseline.json"

        # First run: create baseline
        _run("analyze", str(robot_file), "--baseline", str(baseline), "--no-fail")

        # Second run: all findings should be suppressed → exit 0, no new findings
        result = _run("analyze", str(robot_file), "--baseline", str(baseline))

        assert result.returncode == 0
        assert "suppressed" in result.stderr

    def test_second_run_summary_shows_counts(self, tmp_path: Path) -> None:
        robot_file = tmp_path / "suite.robot"
        robot_file.write_text(_SLEEP_ROBOT, encoding="utf-8")
        baseline = tmp_path / "baseline.json"

        _run("analyze", str(robot_file), "--baseline", str(baseline), "--no-fail")
        result = _run("analyze", str(robot_file), "--baseline", str(baseline), "--no-fail")

        assert "new" in result.stderr
        assert "suppressed" in result.stderr

    def test_update_baseline_refreshes_file(self, tmp_path: Path) -> None:
        robot_file = tmp_path / "suite.robot"
        robot_file.write_text(_SLEEP_ROBOT, encoding="utf-8")
        baseline = tmp_path / "baseline.json"

        # First run: create baseline
        _run("analyze", str(robot_file), "--baseline", str(baseline), "--no-fail")

        # Modify the robot file to introduce a different finding set
        robot_file.write_text(
            _SLEEP_ROBOT + "\nAnother Test\n    Sleep    5s\n", encoding="utf-8"
        )

        result = _run(
            "analyze", str(robot_file), "--baseline", str(baseline), "--update-baseline", "--no-fail"
        )

        assert result.returncode == 0
        assert "baseline" in result.stderr.lower()

    def test_new_finding_not_in_baseline_exits_one(self, tmp_path: Path) -> None:
        robot_file = tmp_path / "suite.robot"
        robot_file.write_text(_SLEEP_ROBOT, encoding="utf-8")
        baseline = tmp_path / "baseline.json"

        # First run: create baseline with current findings
        _run("analyze", str(robot_file), "--baseline", str(baseline), "--no-fail")

        # Add a new sleep on a different line → new finding not in baseline
        robot_file.write_text(
            _SLEEP_ROBOT + "\nNew Test\n    Sleep    3s\n", encoding="utf-8"
        )

        result = _run("analyze", str(robot_file), "--baseline", str(baseline))

        # Has new findings → exit 1
        assert result.returncode == 1

    def test_invalid_baseline_file_exits_error(self, tmp_path: Path) -> None:
        robot_file = tmp_path / "suite.robot"
        robot_file.write_text(_SLEEP_ROBOT, encoding="utf-8")
        baseline = tmp_path / "baseline.json"
        baseline.write_text("{invalid json", encoding="utf-8")

        result = _run("analyze", str(robot_file), "--baseline", str(baseline))

        assert result.returncode == 2
        assert "error" in result.stderr.lower()
