# tests/integration/test_cli_subprocess.py
"""Component / integration tests for the CLI via subprocess (Task 27).

These tests exercise the full command including entry-point resolution,
exit codes, and output format — not just the internal ``_run_analyze`` helper.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest


def _extract_json_array(output: str) -> list:
    """Extract the last JSON array from stdout (logs may precede it)."""
    # Split on newlines and find the first line starting with '['
    for i, line in enumerate(output.splitlines()):
        stripped = line.strip()
        if stripped.startswith("["):
            # Found the start of the JSON array; reconstruct from here
            json_str = "\n".join(output.splitlines()[i:])
            return json.loads(json_str)
    return []


def _run(*args: str, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    """Run robot-optimizer as a module so it works without install."""
    cmd = [sys.executable, "-m", "robot_optimizer_core", *args]
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=cwd,
    )


# ---------------------------------------------------------------------------
# --version
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestVersionSubprocess:
    def test_version_exits_zero(self) -> None:
        result = _run("--version")
        assert result.returncode == 0
        assert "robot-optimizer" in result.stdout.lower() or result.returncode == 0


# ---------------------------------------------------------------------------
# analyze — exit codes
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestAnalyzeExitCodesSubprocess:
    def test_clean_file_exits_zero(self, tmp_path: Path) -> None:
        """A file with no findings should exit 0."""
        f = tmp_path / "clean.robot"
        f.write_text("*** Test Cases ***\nMy Test\n    Log    hello\n")
        result = _run("analyze", str(f))
        # Exit 0 or 1 (findings may be generated by default analyzers)
        assert result.returncode in (0, 1)

    def test_missing_path_exits_two(self, tmp_path: Path) -> None:
        """A nonexistent path must exit with code 2."""
        result = _run("analyze", str(tmp_path / "nosuchfile.robot"))
        assert result.returncode == 2

    def test_no_fail_exits_zero(self, tmp_path: Path) -> None:
        """--no-fail must produce exit 0 even when findings exist."""
        f = tmp_path / "t.robot"
        f.write_text(
            "*** Test Cases ***\nMy Test\n    Sleep    10\n"
        )
        result = _run("analyze", str(f), "--no-fail")
        assert result.returncode == 0


# ---------------------------------------------------------------------------
# analyze — output format
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestAnalyzeFormatSubprocess:
    def test_json_output_is_valid_json(self, tmp_path: Path) -> None:
        f = tmp_path / "t.robot"
        f.write_text(
            "*** Test Cases ***\nMy Test\n    Sleep    10\n"
        )
        result = _run("analyze", str(f), "--format", "json")
        parsed = _extract_json_array(result.stdout)
        assert isinstance(parsed, list)

    def test_text_output_contains_finding_info(self, tmp_path: Path) -> None:
        f = tmp_path / "t.robot"
        f.write_text(
            "*** Test Cases ***\nMy Test\n    Sleep    10\n"
        )
        result = _run("analyze", str(f), "--format", "text")
        # Either findings or a clean message
        assert result.stdout


# ---------------------------------------------------------------------------
# analyze — --min-severity (Task 17)
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestMinSeveritySubprocess:
    def test_min_severity_error_filters_warnings(self, tmp_path: Path) -> None:
        """With --min-severity ERROR, WARNING findings must not appear."""
        f = tmp_path / "t.robot"
        f.write_text(
            "*** Test Cases ***\nMy Test\n    Sleep    2\n"
        )
        result = _run("analyze", str(f), "--format", "json", "--min-severity", "ERROR")
        findings = _extract_json_array(result.stdout)
        severities = {finding["severity"] for finding in findings}
        assert "WARNING" not in severities
        assert "INFO" not in severities

    def test_invalid_min_severity_exits_two(self, tmp_path: Path) -> None:
        f = tmp_path / "t.robot"
        f.write_text("*** Test Cases ***\nMy Test\n    Log    hi\n")
        result = _run("analyze", str(f), "--min-severity", "CRITICAL")
        assert result.returncode == 2


# ---------------------------------------------------------------------------
# list-analyzers (Task 16)
# ---------------------------------------------------------------------------


@pytest.mark.integration
class TestListAnalyzersSubprocess:
    def test_list_analyzers_text_exits_zero(self) -> None:
        result = _run("list-analyzers")
        assert result.returncode == 0
        assert "dead_code" in result.stdout

    def test_list_analyzers_json_is_valid(self) -> None:
        result = _run("list-analyzers", "--format", "json")
        assert result.returncode == 0
        # Extract the JSON array from stdout (logs may precede it)
        parsed = _extract_json_array(result.stdout)
        assert isinstance(parsed, list)
        names = [r["name"] for r in parsed]
        assert "dead_code" in names
        assert "sleep_detector" in names
        assert "naming_convention" in names

    def test_all_new_analyzers_listed(self) -> None:
        result = _run("list-analyzers", "--format", "json")
        parsed = _extract_json_array(result.stdout)
        names = {r["name"] for r in parsed}
        expected = {
            "dead_code",
            "sleep_detector",
            "hardcoded_value",
            "naming_convention",
            "setup_teardown",
            "tag_consistency",
            "test_documentation",
        }
        assert expected.issubset(names)
